# Generated by Django 3.0.4 on 2020-03-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacher_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meeting_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('repeat', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('links', models.CharField(max_length=2048)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Groups')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Teachers'),
        ),
    ]
