# Generated by Django 3.0.4 on 2020-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200320_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_key',
            field=models.CharField(max_length=256),
        ),
    ]
