# Generated by Django 3.0.4 on 2020-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200320_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='links',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='repeat',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
