# Generated by Django 3.0.4 on 2020-03-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200320_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='teacher',
            new_name='user',
        ),
    ]
