# Generated by Django 3.0.4 on 2020-03-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200320_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.TimeField(default='01:00'),
        ),
    ]
