# Generated by Django 3.0.4 on 2020-03-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200321_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='repeat',
        ),
    ]
